### ISSUE TITLE
Bower warning about minified files

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/fixtable-core#13]
When I check this project out and run `npm install` / `bower install`, I see the following warning/error from Bower:

`bower invalid-meta The "main" field cannot contain minified files`

It seems like the fix for this is as simple as updating the following line in bower.json from this:
`"main": ["dist/fixtable.min.css", "dist/fixtable.min.js"],`
To this:
`"main": ["dist/fixtable.css", "dist/fixtable.js"],`

I'm planning to submit a pull request to fix this, unless there's a particular reason why this should stay the way it is.

**Comment by michaelmcauley** [comment]
Sure, sounds good. I didn't realize that's what the spec called for 👍
