### ISSUE TITLE
Publish this as an NPM package

### ISSUE THREAD

**Issue by menewman** [MyPureCloud/fixtable-core#16]
It would be nice to have `fixtable` published to NPM (in addition to Bower). Then, we wouldn't have to deal with mixing NPM and Bower dependencies when using this via the `fixtable-ember` Ember addon, which has a Bower dependency on this project.

I could submit a PR for this at some point.

**Comment by smargovsky** [comment]
👍 x 10,000 - bumping this!

**Comment by michaelmcauley** [comment]
Done!

https://www.npmjs.com/package/fixtable
